=== openintegrationhub/Connectors/Adapters/AdapterJsonSchema.json
{
  "definitions": {
    "viewClass": {
      "type": "string",
      "enum": ["TextFieldView", "TextAreaView ", "SelectView", "CheckBoxView", "PasswordFieldView", "OAuthFieldView", "CodeFieldView", "JSONataView", "WebHookPayloadView", "CSVReadView"],
      "description": "To be done",
      "default": "TextFieldWithNoteView",
      "examples": [
        "TextFieldWithNoteView"
      ]
    },
    "fields": {
      "type": "object",
      "minProperties": 1,
      "patternProperties": {
        "[a-z]+": {
          "type": "object",
          "minProperties": 3,
          "required": [
            "label",
            "required",
            "viewClass"
          ],
          "properties": {
            "label": {
              "type": "string",
              "description": "What is the purpose of this field",
              "default": "Example lable"
            },
            "required": {
              "type": "boolean",
              "default": true
            },
            "viewClass" : {
              "$ref": "#/definitions/viewClass"
            }
          }  
        }
      }  
    }
  },
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "required": [
    "title",
    "description",
    "credentials"
  ],
  "properties": {
    "title": {
      "type": "string",
      "description": "An explanation about the purpose of this instance.",
      "default": "Component name",
      "examples": [
        "Petstore API (Node.js)"
      ]
    },
    "description": {
      "type": "string",
      "description": "An explanation about the purpose of this instance.",
      "default": "Your component description",
      "examples": [
        "elastic.io component for the Petstore API"
      ]
    },
    "docsUrl": {
      "type": "string",
      "description": "An explanation about the purpose of this instance.",
      "format": "uri",
      "default": "https://linkToYourDocs.com",
      "examples": [
        "https://github.com/elasticio/petstore-component-nodejs"
      ]
    },
    "credentials": {
      "type": "object",
      "minProperties": 1,
      "required": [
        "fields"
      ],
      "properties": {
        "fields": {"$ref": "#/definitions/fields"}
      }
    },
    "triggers": {
      "type": "object",
      "minProperties": 1,
      "patternProperties": {
        "[a-z]+": {
          "type": "object",
          "minProperties": 3,
          "description" : "To be done",
          "required": [
            "main",
            "type",
            "title"
          ],
          "properties": {
            "main": {
              "type": "string",
              "description": "To be done",
              "default": "Path to trigger.js",
              "examples": [
                "./lib/triggers/getPetsByStatusWithGenerators.js"
              ]
            },
            "type": {
              "type": "string",
              "enum": ["polling", "webhook"],
              "description": "Defines if the trigger is a polling or webhook trigger",
              "default": "polling",
              "examples": [
                "polling"
              ]
            },
            "title": {
              "type": "string",
              "description": "Descriptive name of the trigger",
              "default": "Trigger title",
              "examples": [
                "Get Pets By Status With Generators"
              ]
            },
            "fields": {"$ref": "#/definitions/fields"},
            "metadata": {
              "type": "object",
              "properties": {
                "out": {
                  "type": ["object","string"],
                  "description": "Metadata defining the structure of the output messages.",
                  "default": "path to out metadata ",
                  "examples": [
                    "./lib/schemas/getPetsByStatus.out.json"
                  ]
                }
              }
            },
            "dynamicMetadata": {
              "type": "boolean",
              "description": "Defines dynamic Metadata is supported/enabled",
              "default": false,
              "examples": [
                true
              ]
            }
          }
        }
      }
    },
    "actions": {
      "type": "object",
      "minProperties": 1,
      "patternProperties": {
        "[a-z]+": {
          "type": "object",
          "minProperties": 3,
          "description" : "To be done",
          "required": [
            "main",
            "title"
          ],
          "properties": {
            "main": {
              "type": "string",
              "description": "To be done",
              "default": "Path to action .json",
              "examples": [
                "./lib/actions/createPetWithPromise.js"
              ]
            },
            "title": {
              "type": "string",
              "description": "Descriptive name of the action",
              "default": "Title Name",
              "examples": [
                "Create a Pet With Promise"
              ]
            },
            "metadata": {
              "type": "object",
              "minProperties": 2,
              "required": [
                "in",
                "out"
              ],
              "properties": {
                "in": {
                  "type": ["string", "object"],
                  "description": "Source of the metdata. Either a path to a json schema(string) or an inline json schema (object)",
                  "default": "Path to in metadata",
                  "examples": [
                    "./lib/schemas/createPet.in.json"
                  ]
                },
                "out": {
                  "type": ["string", "object"],
                  "description": "Metadata defining the structure of the output messages.",
                  "default": "Path to out metadata",
                  "examples": [
                    "./lib/schemas/createPet.out.json"
                  ]
                }
              }
            },
            "dynamicMetadata": {
              "type": "boolean",
              "description": "Defines dynamic Metadata is supported/enabled",
              "default": false,
              "examples": [
                true
              ]
            }
          }
        }
      }
    }
  }
}

=== openintegrationhub/Connectors/Adapters/Examples/SnazzyContactsAdapter/component.json
{
  "title": "Snazzy Contacts",
  "description": "Snazzy Contacts component for the elastic.io platform",
  "docsUrl": "https://snazzycontacts.com",
  "credentials": {
    "fields": {
      "apikey": {
        "label": "API key for data sharing",
        "required": true,
        "viewClass": "TextFieldWithNoteView",
        "note": "Please use <b>Snazzy Contacts</b> API key."
      },
      "email": {
        "label": "Your email",
        "required": true,
        "viewClass": "TextFieldView",
        "note": "Use your email registerd in Snazzy Contacts"
      },
      "password": {
        "label": "Your password",
        "required": true,
        "viewClass": "TextFieldView",
        "note": "Use your password for Snazzy Contacts"
      }
    }
  },
  "triggers": {
    "getPersonsPolling": {
      "main": "./lib/triggers/getPersonsPolling.js",
      "type": "polling",
      "description": "Fetch all persons from snazzycontacts saved by the user",
      "title": "Get Persons",
      "metadata": {
        "out": "./lib/schemas/getPersons.out.json"
      }
    },
    "getOrganizationsPolling": {
      "main": "./lib/triggers/getOrganizationsPolling.js",
      "type": "polling",
      "description": "Fetch all organizations from snazzycontacts saved by the user",
      "title": "Get Organizations",
      "metadata": {
        "out": "./lib/schemas/getOrganizations.out.json"
      }
    }
  },
  "actions": {
    "createPerson": {
      "main": "./lib/actions/createPerson.js",
      "title": "Create Person",
      "description": "Create a new person in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/createPerson.in.json",
        "out": "./lib/schemas/createPerson.out.json"
      }
    },
    "createOrganization": {
      "main": "./lib/actions/createOrganization.js",
      "title": "Create Organization",
      "description": "Create an organization in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/createOrganization.in.json",
        "out": "./lib/schemas/createOrganization.out.json"
      }
    },
    "updatePerson": {
      "main": "./lib/actions/updatePerson.js",
      "title": "Update Person",
      "description": "Update a person in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/updatePerson.in.json",
        "out": "./lib/schemas/updatePerson.out.json"
      }
    },
    "updateOrganization": {
      "main": "./lib/actions/updateOrganization.js",
      "title": "Update Organization",
      "description": "Update an organization in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/updateOrganization.in.json",
        "out": "./lib/schemas/updateOrganization.out.json"
      }
    },
    "updatePersonsOrganization": {
      "main": "./lib/actions/updatePersonsOrganization.js",
      "title": "Update Person`s Organization",
      "description": "Add a person to more than one organization",
      "metadata": {
        "in": "./lib/schemas/updatePersonsOrganization.in.json",
        "out": "./lib/schemas/updatePersonsOrganization.out.json"
      }
    },
    "deletePerson": {
      "main": "./lib/actions/deletePerson.js",
      "title": "Delete Person",
      "description": "Delete a person in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/deletePerson.in.json",
        "out": "./lib/schemas/deletePerson.out.json"
      }
    },
    "deleteOrganization": {
      "main": "./lib/actions/deleteOrganization.js",
      "title": "Delete Organization",
      "description": "Delete an organization in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/deleteOrganization.in.json",
        "out": "./lib/schemas/deleteOrganization.out.json"
      }
    }
  }
}

=== openintegrationhub/Connectors/Adapters/Examples/SilverpContactsAdapter/component.json
{
  "title": "SilverERP",
  "description": "elastic.io component for the SilverERP API",
  "docsUrl": "https://www.silvererp.com",
  "credentials": {
    "fields": {
      "apiKey": {
        "label": "API key",
        "required": true,
        "viewClass": "TextFieldWithNoteView",
        "note": "Please use the <b>silvererp</b> API key."
      }
    }
  },
  "triggers": {
    "getPersons": {
      "main": "./lib/triggers/getPersons.js",
      "type": "polling",
      "description": "Fetch all persons from silvererp",
      "title": "Get Persons",
      "metadata": {
        "out": "./lib/schemas/getPersons.out.json"
      }
    }
  },
  "actions": {
    "createPerson": {
      "main": "./lib/actions/createPerson.js",
      "title": "Create Person",
      "description": "Create a new person in snazzycontacts",
      "metadata": {
        "in": "./lib/schemas/createPerson.in.json",
        "out": "./lib/schemas/createPerson.out.json"
      }
    }
  }
}
